language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t krishnapulipati/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true krishnapulipati/docker-react npm run test -- --coverage